### ISSUE TITLE
Site Redirect Loop during Development

### ISSUE THREAD

**Issue by M-DEV-1** [meshery/meshery.io#2266]
### Description
When I'm working on a certain page on the site, sometimes it gets stuck within a redirect loop and it won't render new changes, making it difficult to make good updates.

### Environment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://meshery.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](/community#discussion-forums) and [Community Slack](https://slack.meshery.io)

**Comment by M-DEV-1** [comment]
Sharing the current development configuration for Meshery (`_config-dev.yml`) for context and troubleshooting.

<details>
<summary>Click to expand <code> _config-dev.yml</code></summary>

```yaml
# ----
# Site

title: Meshery
url: "https://meshery.io"
baseurl: ""
google_analytics_key: UA-152604689-1
google_maps_javascript_api_key:
disqus_shortname:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /assets/images/logos/meshery-gradient.png
description: The extensible cloud native manager. Confidently wrangle cloud native infrastructure with Meshery.
author:
  name: The Meshery Authors
  email: community@meshery.io
  twitter: mesheryio
social:
  name: Meshery
  links:
    - https://github.com/meshery/meshery.io

# -----
# Colors
coolgray: "#3C494F"
lightgreen: "#00D3A9"
darkgreen: "#00B39F"

# -----
# Build

plugins:
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - octopress-paginate

timezone: Etc/UTC

collections_dir: collections
collections:
  charts:
    output: false
  contributors:
    output: true
    permalink: /community/members/:name
  extensions:
    output: true
    permalink: /:collection/:name
    sort_by: name
  pages:
    output: true
  programs:
    output: true
  catalog:
    output: true
    # sort_by: patternId
  models:
    output: true
    permalink: /catalog/:collection/:name
    sort_by: name
  filters:
    output: true
    permalink: /catalog/:collection/:name
    sort_by: name
  handbook:
    output: true
    permalink: /community/:collection/:name
  custom-models:
    output: true
    permalink: /catalog/models/:name

# Post URL format
permalink: /blog/:year/:month/:name/

# paginate: 5
# paginate_path: "/blog/:num/"

# # Site configuration for the Jekyll 3 Pagination Gem
# # The values here represent the defaults if nothing is set
# pagination:
#   enabled: true
#   per_page: 2
#   permalink: "/page/:num/"
#   title: " - page :num"
#   limit: 0
#   sort_field: "date"
#   sort_reverse: true
pagination:
  per_page: 6
  permalink: "/page:num"

#   # Site-wide kill switch, disabled here it doesn't run at all
#   enabled: true

#   # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
#   debug: false

#   # The default document collection to paginate if nothing is specified ('posts' is default)
# collection: 'posts'

#   # How many objects per paginated page, used to be `paginate` (default: 0, means all)
# per_page: 5

#   # The permalink structure for the paginated pages (this can be any level deep)
# permalink: /blog/:category/:title
# permalink: pretty
#   permalink: '/page/:num/' # Pages are index.html inside this folder (default)
#   #permalink: '/page/:num.html' # Pages are simple html files
#   #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.

#   # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
#   title: ':title - page :num'

#   # Limit how many pagenated pages to create (default: 0, means all)
#   limit: 0

#   # Optional, defines the field that the posts should be sorted on (omit to default to 'date')
#   sort_field: 'patternId'

#   # Optional, sorts the posts in reverse order (omit to default decending or sort_reverse: true)
#   sort_reverse: false

#   # Optional, the default category to use, omit or just leave this as 'posts' to get a backwards-compatible behavior (all posts)
#   category: 'posts'

#   # Optional, the default tag to use, omit to disable
#   tag: ''

#   # Optional, the default locale to use, omit to disable (depends on a field 'locale' to be specified in the posts,
#   # in reality this can be any value, suggested are the Microsoft locale-codes (e.g. en_US, en_GB) or simply the ISO-639 language code )
#   locale: ''

#  # Optional,omit or set both before and after to zero to disable.
#  # Controls how the pagination trail for the paginated pages look like.
#   trail:
#     before: 2
#     after: 2

#   # Optional, the default file extension for generated pages (e.g html, json, xml).
#   # Internally this is set to html by default
#   extension: html

#   # Optional, the default name of the index file for generated pages (e.g. 'index.html')
#   # Without file extension
#   indexpage: 'index'

############################################################

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "plain"
  - scope:
      path: ""
      type: "posts"
      permalink: '/blog/:year/:month/:name/'
    values:
      layout: "post"
      _options:
        content:
          width: 1500
          height: 2500
  - scope:
      path: ""
      type: "catalog"
    values:
      _options:
        image:
          width: 600
          height: 600

  - scope:
      path: ""
      type: "contributors"
    values:
      _options:
        image_path:
          width: 600
          height: 600
  - scope:
      path: ""
    values:
      layout: "page"
  - scope:
      path: "programs.html"
    values:
      layout: "default"
  - scope:
      path: "index.html"
    values:
      layout: "default"
  - scope:
      path: "contact.html"
    values:
      full_width: true

jekyll-archives:
  enabled:
    - categories
  permalinks:
    category: '/blog/category/:name/'

markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE

# -----------
# Hydra

social_icons:
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - RSS
  - Bluesky

_comments:
  map: Update the map location and display settings.
  latitude: Coordinates for the center marker on the map.
  longitude: Coordinates for the center marker on the map.
  zoom: The zoom level for the map.
  features_table: Update the information in the pricing tables.
  highlight: Emphasis the text
  color: The background colour used in the plan name and call to action.
  new_window: Open link in new window

```
</details>

// @vishalvivekm
